defaults:
  - _self_
  - task/tokenizer: libero/libero_object_medium

name: train_oattok_object_medium_cpu
_target_: oat.workspace.train_oattok.TrainOATTokWorkspace

seed: 42
horizon: 32
task_name: ${task.tokenizer.name}
action_dim: ${task.tokenizer.shape_meta.action.shape[0]}

latent_dim: ${eval:'len(${tokenizer.quantizer.levels})'}
tokenizer:
  _target_: oat.tokenizer.oat.tokenizer.OATTok

  encoder:
    _target_: oat.tokenizer.oat.encoder.register_encoder.RegisterEncoder
    sample_dim: ${action_dim}
    sample_horizon: ${horizon}
    emb_dim: 128
    head_dim: 32
    depth: 1
    pdropout: 0.1
    latent_dim: ${latent_dim}
    num_registers: 8

  decoder:
    _target_: oat.tokenizer.oat.decoder.single_pass_decoder.SinglePassDecoder
    sample_dim: ${action_dim}
    sample_horizon: ${horizon}
    emb_dim: 128
    head_dim: 32
    depth: 2
    pdropout: 0.1
    token_dropout_mode: 'pow2'
    latent_dim: ${latent_dim}
    latent_horizon: ${tokenizer.encoder.num_registers}
    use_causal_decoder: true

  quantizer:
    _target_: oat.tokenizer.oat.quantizer.fsq.FSQ
    levels: [8, 5, 5, 5]

training:
  resume: false
  allow_bf16: false
  max_grad_norm: 1.0
  num_epochs: 8
  val_every: 2
  sample_every: 2
  checkpoint_every: 2
  lr_scheduler: constant
  lr_warmup_steps: 0
  gradient_accumulate_every: 1
  max_train_steps: 20
  max_val_steps: 5
  max_reconst_steps: 5
  seed: ${seed}
  use_ema: false
  num_demo: 100
  tqdm_interval_sec: 1.0

ema:
  _target_: oat.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

optimizer:
  learning_rate: 5.0e-5
  weight_decay: 0.0
  betas: [0.9, 0.95]

dataloader:
  batch_size: 4
  num_workers: 0
  shuffle: true
  pin_memory: false
  persistent_workers: false
  drop_last: false

val_dataloader:
  batch_size: 4
  num_workers: 0
  shuffle: false
  pin_memory: false
  persistent_workers: false
  drop_last: false

logging:
  project: oat_cpu_object_medium
  resume: false
  mode: offline
  name: ${now:%Y%m%d.%H%M%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "cpu", "object-medium"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_reconst_mse
    mode: min
    k: 1
    format_str: 'ep-{epoch:04d}_mse-{test_reconst_mse:.3f}.ckpt'
  save_last_ckpt: true
  save_last_snapshot: false

multi_run:
  run_dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y%m%d.%H%M%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}
  sweep:
    dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
